import Image from "next/image"
import { Wordmark } from "@/components/typography/wordmark"

// Bank details are rendered as a committed raster (generated by
// scripts/generate-pay-image.ts) so the account numbers exist only as pixels —
// not selectable, copyable, or scrapeable text. The alt text is deliberately
// generic and contains none of the sensitive values.
export default function PayPage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center px-6 py-16">
      <div className="flex w-full max-w-[560px] flex-col items-center text-center">
        <Wordmark size="lg" href="/en/" />

        <h1 className="mt-8 text-display-l font-bold tracking-tight text-ink">
          Payment Details
        </h1>

        <Image
          src="/pay/bank-details.png"
          alt="Swiss Controls bank payment details, shown as an image"
          width={680}
          height={749}
          priority
          className="mt-8 h-auto w-full rounded-2xl"
        />
      </div>
    </main>
  )
}
